### PR TITLE
Merge 'hello-git' branch into 'squashing' branch and squash commits

### PR DESCRIPTION
**Pull request by blunterdecosta123**
Initial commit: This commit adds the program to print "Hello, World" to the file hello.py.

in is the final git commit
Merge branch 'hello-git' into squashing: This commit resolves the merge conflict in hello.py by including both "Hello, World" and "Hello, git" print statements.

### CODE REVIEW

**Comment by umeshSinghVerma** [comment]
Hii @blunterdecosta123 
It seems like you have directly write 
```   
cout<<"Hello World"<<endl;
cout<<"Hello, git"<<endl;
```

Please ensure you follow the guidelines provided in https://github.com/iiitl/git-practice-weekend-24/blob/main/SQUASH_AND_MERGE.md.
Thank you.

**Comment by blunterdecosta123** [comment]
No sir it was giving merge conflict and I simply delete the lines git added to end up with something like:
print("Hello, World")
print("Hello, git")

**Comment by umeshSinghVerma** [comment]
@blunterdecosta123, you should have two commits in the squashing branch: one adding "Hello World" and another about the merge. However, in the pull request, there is only a single commit.
Please ensure that both commits are included in the pull request.

**Comment by umeshSinghVerma** [comment]
@blunterdecosta123, you should have two commits in the squashing branch: one adding "Hello World" and another about the merge. However, in the pull request, there is only a single commit.
Please ensure that both commits are included in the pull request.

**Pull request closed without merging**
